### ISSUE TITLE
versioned route files

### ISSUE THREAD

**Issue by jaygoodfellow** [iamchristopher/restify-route-loader#4]
Enhancement request to add the ability to version the routes via their file name `get-1.0.0.js` in addition to the current method of having all versions within an array inside of get.js. Maintaining 3 or 4 different versions of a route becomes cumbersome when they are within the same file. 

Not sure how you would handle discrepancies between the version in the file name vs the version inside, which one would supersede the other and allowing for a mix of both types of versioning.

**Comment by jorbascrumps** [comment]
Great idea! I would consider the filename version to be more explicit than a value defined inside, thus taking precedence.

**Comment by jorbascrumps** [comment]
@jaygoodfellow This is available for testing in #7.

**Comment by jorbascrumps** [comment]
Resolved by #7.
