### ISSUE TITLE
Empty file crashes restify

### ISSUE THREAD

**Issue by jaygoodfellow** [iamchristopher/restify-route-loader#9]
Creating an empty route file causes an error.

`TypeError: Cannot read property 'forEach' of undefined
  at /node_modules/restify-route-loader/dist.js:52:21
  at Array.map (<anonymous>)
  at /node_modules/restify-route-loader/dist.js:32:22`

**Comment by jorbascrumps** [comment]
I think there's 2 options for handling this scenario:
1. Exit with a more descriptive message; or
2. Emit a warning and continue

**Comment by jorbascrumps** [comment]
@jaygoodfellow this is ready for testing in #10.

**Comment by jorbascrumps** [comment]
Resolved by #10
